name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  solidity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Wake
        uses: Ackee-Blockchain/wake-setup-action@0.1.0

      - name: Install Solidity dependencies (Soldeer)
        run: forge soldeer update

      - name: Check formatting (Foundry)
        run: forge fmt --check

      - name: Detect all (Wake)
        run: wake detect all

#      - name: Static analysis (Wake)
#        id: wake-detect
#        continue-on-error: true
#        uses: Ackee-Blockchain/wake-detect-action@0.1.0
#        with:
#          config-path: wake.toml
#          export-sarif: true

#      - name: Upload Wake SARIF
#        uses: github/codeql-action/upload-sarif@v4
#        with:
#          sarif_file: ${{ steps.wake-detect.outputs.sarif }}
#          checkout_path: ${{ github.workspace }}

      - name: Generate pytypes (Wake)
        run: wake up pytypes

      - name: Test (Wake)
        run: wake test tests

      - name: Fail if static analysis did not pass
        if: steps.wake-detect.outcome == 'failure'
        run: exit 1
